spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurants
    username: postgres
    password: simple123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update